<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Consolidate the two fingerprint-related indexes into a single, explicitly
 * named unique constraint.
 *
 * Before:
 *   - UNIQ_802A3918FC0B754A  (unique)      – auto-generated by ORM column unique:true
 *   - idx_fingerprint         (non-unique)  – redundant lookup index
 *
 * After:
 *   - uniq_fingerprint        (unique)      – explicit, readable name
 */
final class Version20260320000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace auto-named fingerprint unique index and redundant non-unique index with a single named unique constraint';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP INDEX IF EXISTS "UNIQ_802A3918FC0B754A"');
        $this->addSql('DROP INDEX IF EXISTS idx_fingerprint');
        $this->addSql('CREATE UNIQUE INDEX uniq_fingerprint ON transfers (fingerprint)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX IF EXISTS uniq_fingerprint');
        $this->addSql('CREATE UNIQUE INDEX "UNIQ_802A3918FC0B754A" ON transfers (fingerprint)');
        $this->addSql('CREATE INDEX idx_fingerprint ON transfers (fingerprint)');
    }
}

